### PR TITLE
Set up User's Login form

### PR DESCRIPTION
**Pull request by ekiira**
What does this PR do?
   Closes issues #7  

 Description of Task to be completed?
   Created a login form for book gallery users

 How should this be manually tested?
   running ( npm start ) then add '/login' to the url path

Screenshots (if appropriate)
Screenshot 2020-07-25 at 12 07 00

### CODE REVIEW

**Review by mazma1 — COMMENTED** [review]
@ekiira ~when I go to `/login` on the review app, it doesn't load the component so I am unable to test this out, I'm trying to find out what the problem is.~ 

This has now been fixed, https://deploy-preview-18--booksgallery.netlify.app/login works.


Here's one change I'll like you to make:
We don't really have an index page so the login page will be the first page users see (instead of that counter that was used for testing the setup). Can you try to see how you can update this so that when a user visits the index `/` page, he/she is redirected to `/login`?

**Review by mazma1 — CHANGES_REQUESTED** [review]
I tested locally and this is what I have:

Screenshot 2020-07-31 at 09 26 09

This is a really close design, well done! A few things that can be improved:
- "Superb" in SuperbBooks should have an emphasis.
- Can the gray texts be a little darker? Especially those in the input fields (they are not so easy to read because of the gray background). The placeholder texts are fine, they are legible.
- Let the login form be vertically centered as well.

**Comment by ekiira** [comment]
okay, thank you. I'll make the changes

**Comment by mazma1** [comment]
Was reopened [here](https://github.com/she-code-africa/WOSCA-book-gallery/pull/19)

**Pull request closed without merging**
